POST http://localhost:3001/api/auth/
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiZGVzY29udHJvbCIsIm5hbWUiOiJyaG9qZXIiLCJub3RlcyI6WyI2MjI1MGZhMjE3MzFlNDUzODM2NjQzNDgiLCI2MjI3ZjUyZWRiZWNlZDhhNjNiZGE4ZWEiLCI2MjI3ZmNlN2E0ZDVmODlhMDAxNmQ3ODEiLCI2MjJhNDE2MDJhNTdhZWIzMTc3ZWVmMmUiLCI2MjJhNDFhYjMwNWI0ZTIyNjNlOTAyNTQiLCI2MjJhNGY1NjNlYTQzMTZiOWY4ZmMxMDUiLCI2MjJhNTBmNmExZDBjMzk1MzYxMDBhYzEiLCI2MjJhNTFiYmExZDBjMzk1MzYxMDBhZDAiLCI2MjJhNTFlZjcwMDk3YzViMjRhYzU5NjMiLCI2MjJkNWM2YWNiZDJmYWY2ZWM0NDQxODYiLCI2MjJkNWU0NGNiZDJmYWY2ZWM0NDQxOWEiLCI2MjJkNjYxODczMDA5MGFmNGMzYjIxMDIiXSwiaWQiOiI2MjI1MGY4NTE3MzFlNDUzODM2NjQzNDMifSwiaWF0IjoxNjQ3MTUwMzQ5LCJleHAiOjE2NDcxNTM5NDl9.sZcz-G6xLJnQOskl5kt-Yx4syPwZwIRdLSq3OXnAP_c

{
    
}